# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Category.all.each {|x| x.destroy }
Video.all.each {|x| x.destroy }

Category.create(name: 'Comedy')
Category.create(name: 'Drama')
Category.create(name: 'Television')
Category.create(name: 'Fantasy')
Category.create(name: 'Sci-fi')
Category.create(name: 'Action')

Video.create(title: 'Wizard People, Dear Reader', description: 'Wizard People, Dear Reader is a narrative retelling of the lives of the characters of The Sorcerers Stone and the world in which they live. Presented in the form of a thirty-five chapter audiobook, this soundtrack is intended to replace the films audio track.', small_cover_url: '/tmp/wizard_people_dear_reader.jpg', large_cover_url: '/tmp/wizard_people_dear_reader.jpg', category_ids: Category.where(name: 'Comedy').first.id)
Video.create(title: 'Waking Life', description: 'The film explores a wide range of philosophical issues including the nature of reality, dreams, consciousness, the meaning of life, free will, and existentialism. Waking Life is centered on a young man who wanders through a variety of dream-like realities wherein he encounters numerous individuals who willingly engage in insightful philosophical discussions.', small_cover_url: '/tmp/waking_life.jpg', large_cover_url: '/tmp/waking_life.jpg', category_ids: Category.where(name: 'Drama').first.id)
Video.create(title: 'The Blues Brothers', description: 'The story is a tale of redemption for paroled convict Jake and his brother Elwood, who take on "a mission from God" to save from foreclosure the Catholic orphanage in which they grew up. To do so, they must reunite their R&B band and organize a performance to earn $5,000 needed to pay the orphanages property tax bill.', small_cover_url: '/tmp/the_blues_brothers.jpg', large_cover_url: '/tmp/the_blues_brothers.jpg', category_ids: Category.where(name: 'Comedy').first.id)
Video.create(title: 'Bojack Horseman', description: 'In a world where humans and anthropomorphic animals live side by side, BoJack Horseman, the washed-up star of the 1990s sitcom Horsin Around, plans his big return to celebrity relevance with a tell-all autobiography that he dictates to his ghostwriter Diane Nguyen. BoJack also has to contend with the demands of his agent and on-again-off-again girlfriend Princess Carolyn, the misguided antics of his freeloading roommate Todd Chavez, and his frenemy Mr. Peanutbutter, who is also Nguyens boyfriend. The series satirizes Hollywood, celebrity culture, and the film industry.', small_cover_url: '/tmp/bojack_horseman.jpg', large_cover_url: '/tmp/bojack_horseman.jpg', category_ids: [Category.where(name: 'Television').first.id, Category.where(name: 'Comedy').first.id, Category.where(name: 'Drama').first.id])
Video.create(title: 'Boyhood', description: 'Boyhood is a 2014 American independent coming-of-age drama film, written and directed by Richard Linklater, and starring Patricia Arquette, Ellar Coltrane, Lorelei Linklater, and Ethan Hawke. Shot intermittently from 2002 to 2013, Boyhood depicts the childhood and adolescence of Mason Evans, Jr. (Coltrane) from ages six to eighteen as he grows up in Texas with divorced parents (Arquette and Hawke).', small_cover_url: '/tmp/boyhood.jpg', large_cover_url: '/tmp/boyhood.jpg', category_ids: Category.where(name: 'Drama').first.id)
Video.create(title: 'The Fellowship of the Ring', description: 'Set in Middle-earth, the story tells of the Dark Lord Sauron (Sala Baker), who is seeking the One Ring. The Ring has found its way to the young hobbit Frodo Baggins (Elijah Wood). The fate of Middle-earth hangs in the balance as Frodo and eight companions who form the Fellowship of the Ring begin their journey to Mount Doom in the land of Mordor, the only place where the Ring can be destroyed.', small_cover_url: '/tmp/lotr_fotr.jpg', large_cover_url: '/tmp/lotr_fotr.jpg', category_ids: Category.where(name: 'Fantasy').first.id)
Video.create(title: 'The Empire Strikes Back', description: 'The film is set three years after Star Wars. The Galactic Empire, under the leadership of the villainous Darth Vader and the Emperor Palpatine, is in pursuit of Luke Skywalker and the rest of the Rebel Alliance. While Vader chases a small band of Lukes friends—Han Solo, Princess Leia Organa, and others—across the galaxy, Luke studies the Force under Jedi Master Yoda. When Vader captures Lukes friends, Luke must decide whether to complete his training and become a full Jedi Knight or to confront Vader and save his friends.', small_cover_url: '/tmp/the_empire_strikes_back.jpg', large_cover_url: '/tmp/the_empire_strikes_back.jpg', category_ids: [Category.where(name: 'Sci-fi').first.id, Category.where(name: 'Fantasy').first.id])
Video.create(title: 'Watchmen', description: 'The film is set in an alternate history in the year 1985 at the height of the Cold War between the United States and the Soviet Union, as a group of mostly retired American superheroes investigates an apparent conspiracy against them and uncovers something even more grandiose and sinister, while their moral limitations are challenged by the complex nature of the circumstances.', small_cover_url: '/tmp/watchmen.jpg', large_cover_url: '/tmp/watchmen.jpg', category_ids: Category.where(name: 'Sci-fi').first.id)
Video.create(title: 'Hero', description: 'In ancient China during the Warring States period, the nameless prefect of a small jurisdiction arrives at the Qin states capital city to meet the king of Qin, who has survived an attempt on his life by the assassins Long Sky, Flying Snow, and Broken Sword. Because of the assassination attempt, no visitors are to approach the king within 100 paces. "Nameless" claims that he has slain the three assassins and he displays their weapons before the king, who allows the former to sit closer to him and tell him his story.', small_cover_url: '/tmp/hero.jpg', large_cover_url: '/tmp/hero.jpg', category_ids: [Category.where(name: 'Action').first.id, Category.where(name: 'Fantasy').first.id])
Video.create(title: 'Hobgoblins', description: 'Hobgoblins is a 1988 low-budget indie horror-comedy B-movie directed, written, and produced by Rick Sloane, who also served as cinematographer and editor. The plot concerns small, often considered cheaply designed and made hobgoblins (Small demon like mythical and goblin-like creatures). The film is often seen as a rip-off of "every small monster movie," but mainly Gremlins. The film is generally considered to be of exceptionally poor quality, and has come to be regarded as one of the worst films ever made.', small_cover_url: '/tmp/hobgoblins.jpg', large_cover_url: '/tmp/hobgoblins.jpg', category_ids: [Category.where(name: 'Comedy').first.id, Category.where(name: 'Sci-fi').first.id])
Video.create(title: 'Fargo', description: 'The film is set in 1987, and stars Frances McDormand as a pregnant Minnesota police chief investigating roadside homicides that ensues after a struggling car salesman (William H. Macy) hires two criminals (Steve Buscemi and Peter Stormare) to kidnap his wife in order to extort a hefty ransom from his wealthy father-in-law (Harve Presnell).', small_cover_url: '/tmp/fargo.jpg', large_cover_url: '/tmp/fargo.jpg', category_ids: Category.where(name: 'Comedy').first.id)
Video.create(title: 'Burn After Reading', description: 'Faced with a demotion at work due to a drinking problem, angry Osbourne Cox quits his job as a CIA analyst and resolves to write a memoir about his life and career. When his pediatrician wife Katie finds out, she sees it as a justifiable opportunity to file for divorce and continue her adulterous affair unimpeded. Taking her lawyers advice, she copies financial records and several other files from her husbands computer onto a CD. These files contain a rambling but meaningless diatribe by Cox on purported CIA activities.', small_cover_url: '/tmp/burn_after_reading.jpg', large_cover_url: '/tmp/burn_after_reading.jpg', category_ids: Category.where(name: 'Comedy').first.id)
